### PR TITLE
[Fix] introducing pagination support for comments

### LINKED ISSUE #75: [Bug] Comments don't support pagination
### What happened?

Our App doesn't support pagination of comments. The current implementation fetches [Notion's Comment API](https://developers.notion.com/reference/retrieve-a-comment), which returns max 100 comments. 

We want support pagination comments, like for pages & DBs, which have an existing issue #38 in progress. 

### Steps to reproduce

View comments of a Notion page with 100+ comments

### Relevant ScreenShots

_No response_

### Version

v6.6.5

### What browsers are you seeing the problem on?

Chrome

### PR DESCRIPTION
**Pull request by JeffreytheCoder**
## Issue(s) 

Added pagination support for fetching comments. Now support viewing page with 100+ comments.

Closes #75 

## Proposed changes (including videos or screenshots)

paginated-comments

### CODE REVIEW

File: src/lib/NotionSDK.ts [hunk 1]
```diff
@@ -261,13 +261,20 @@ export class NotionSDK implements INotionSDK {
...
     ): Promise<Array<ICommentInfo> | Error> {
         try {
+            const params: Record<string, string> = {
+                block_id: pageId,
+            };
+
+            if (cursor !== undefined) {
+                params.start_cursor = cursor;
+            }
+
```
Comment (Nabhag8848) [inline src/lib/NotionSDK.ts:275]:
```suggestion
```

Hey @JeffreytheCoder instead of changing JSON with condition in order to match a type, this is a good case to use  short circuiting.

File: src/lib/NotionSDK.ts [hunk 2]
```diff
@@ -261,13 +261,20 @@ export class NotionSDK implements INotionSDK {
...
             const response = await this.http.get(NotionApi.COMMENTS, {
-                params: {
-                    block_id: pageId,
-                },
+                params,
```
Comment (Nabhag8848) [inline src/lib/NotionSDK.ts:277]: @JeffreytheCoder  Something like this. 
```suggestion
      params: {
         block_id: pageId,
         ...(cursor && { start_cursor: cursor }),            
      }
```

**Review by Nabhag8848 — CHANGES_REQUESTED** [review]
Hey @JeffreytheCoder Added one comment, lemme know once you are done, we can merge this. Thanks !

**Comment by JeffreytheCoder** [comment]
> Hey @JeffreytheCoder Added one comment, lemme know once you are done, we can merge this. Thanks !

Good catch! Added the change

**Review by Nabhag8848 — APPROVED** [review]
LGTM 🔥 @JeffreytheCoder  !
