### PR TITLE
[ Fix ] Title Input Visibility When Nothing is Selected in Select Page Dropdown

### LINKED ISSUE #52: [Bug]: In the Create Page or Record modal, the title input text element is always visible.
### What happened?

In the Create Page or Database modal, when selecting a database, a different set of inputs has to be filled. Conversely, when selecting a page, only the title should be filled. However, the title input is visible at all times, even when nothing is selected. This is unexpected behavior because, for both databases and pages, the input requirements are different.

### Steps to reproduce

1. Set up the Rocket Chat Server and install the Notion App following the documentation.
2. Navigate to the Notion Bot.
3. Type /notion create to open the modal.
4. Even if there is no page selected, the title bar is still visible. This has no meaning and constitutes unexpected behavior.

### Relevant ScreenShots

Screenshot from 2024-01-30 02-31-04

### Version

v6.6.0-develop

### What browsers are you seeing the problem on?

Microsoft Edge

### PR DESCRIPTION
**Pull request by Spiral-Memory**
## Issue(s)
Fixed the title input visibility issue; now it will be visible only when a page or database is selected (In the database, additional fetching happens, and that is left as it is).

Closes #52 

## Acceptance Criteria fulfillment

- [x] Identified that the title block is rendered without any condition.
- [x] Added an optional page argument, and the title block will be rendered only when a page or database is selected.
- [x] Updated the modal when a page gets selected, similar to how it was implemented when a database is selected.

## Proposed changes (including videos or screenshots)

[Demo Video Link](https://github.com/RocketChat/Apps.Notion/assets/78961432/7b557725-c647-41ed-85f2-038bd8160667)

### CODE REVIEW

File: src/modals/createPageOrRecordModal.ts [hunk 1]
```diff
@@ -139,8 +140,7 @@ export async function createPageOrRecordModal(
             actionId: NotionPageOrRecord.TITLE_ACTION,
         }
     );
-
-    blocks.push(titleOfPageOrRecordBlock);
+    if(page || parent) blocks.push(titleOfPageOrRecordBlock);
```
Comment (Nabhag8848) [inline src/modals/createPageOrRecordModal.ts:143]:
```suggestion

    if(page || parent) blocks.push(titleOfPageOrRecordBlock);
```

Add space above for readability

File: src/modals/createPageOrRecordModal.ts [hunk 2]
```diff
@@ -42,6 +42,7 @@ export async function createPageOrRecordModal(
     modalInteraction: ModalInteractionStorage,
     tokenInfo: ITokenInfo,
     parent?: IDatabase,
+    page?:IPage,
```
Comment (Nabhag8848) [inline src/modals/createPageOrRecordModal.ts:45]:
```suggestion
    page?: IPage,
```
Also this change. Else Everything LGTM!

**Review by Nabhag8848 — CHANGES_REQUESTED** [review]
@Spiral-Memory Added few comments. lets stick to standards. Will Merge this after I merge Sayan PR. 

Overall LGTM

**Comment by Spiral-Memory** [comment]
> @Spiral-Memory Added few comments. lets stick to standards. Will Merge this after I merge Sayan PR.
> 
> Overall LGTM

Sure @Nabhag8848, I have committed your suggestions. Thanks for the review and feedback. 
However, regarding the review, which formatter should we use to stick to the standards ?

**Review by Nabhag8848 — APPROVED** [review]
LGTM !  @Spiral-Memory 🚀, None Project already have lint set up.

**Comment by Spiral-Memory** [comment]
> LGTM ! @Spiral-Memory 🚀, None Project already have prettier set up.

Okay @Nabhag8848 , Thanks for the input. will make sure to keep things formatted.
